# Generated by Django 3.0.2 on 2020-01-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const',
            old_name='name',
            new_name='const',
        ),
    ]
