# Generated by Django 3.0.2 on 2020-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_app_const'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='const',
            new_name='constructeur',
        ),
    ]
