# Generated by Django 3.0.2 on 2020-01-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20200119_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='constructeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorial.Const'),
        ),
    ]
