# Generated by Django 3.0.2 on 2020-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20200119_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='constructeur',
        ),
        migrations.AddField(
            model_name='app',
            name='constructeur',
            field=models.ManyToManyField(to='tutorial.Const'),
        ),
    ]
