# Generated by Django 3.0.2 on 2020-01-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20200119_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='constructeur',
        ),
        migrations.AddField(
            model_name='app',
            name='constructeur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tutorial.Const'),
            preserve_default=False,
        ),
    ]
