# Generated by Django 3.0.2 on 2020-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_auto_20200119_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const',
            old_name='const',
            new_name='key',
        ),
        migrations.AddField(
            model_name='const',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
